[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Temporarily disable catch-all redirect for AdSense verification
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

# Allow direct access to HTML files for AdSense crawler
[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  force = true
